<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<!-- ====================================================================== -->
	<!-- PARENT                                                                 -->
	<!-- ====================================================================== -->
	<parent>
		<groupId>r01.fabric.coreservices.messaging.kafka.listeners</groupId>
		<artifactId>r01fMessagingKafkaListeners</artifactId>
		<version>${revision}</version>
	</parent>

	<!-- ====================================================================== -->
	<!-- ARTIFACT                                                               -->
	<!-- ====================================================================== -->
	<name>r01fKafkaListenerSpringBaseClasses</name>
	<artifactId>r01fKafkaListenerSpringBaseClasses</artifactId>

	<!-- ====================================================================== -->
	<!-- DEPENDENCIES                                                           -->
	<!-- ====================================================================== -->
	<dependencies>
	<!-- ====================================================================== -->
	<!-- R01FB Businness Spring WEB                                                -->
	<!-- ====================================================================== -->
	

		
	 <!-- ///////////////////////////////////////// -->
	 <!-- Kafka CORE                                -->
	 <!-- ///////////////////////////////////////// -->
        <dependency>
			<groupId>r01.fabric.coreservices.messaging.kafka</groupId>
			<artifactId>r01fMessagingKafkaClasses</artifactId>
			<version>${revision}</version>
		</dependency>
	   <dependency>
			<groupId>r01.fabric.coreservices.messaging.kafka</groupId>
			<artifactId>r01fMessagingKafkaGuiceClasses</artifactId>
			<version>${revision}</version>
		</dependency>
     <!-- ///////////////////////////////////////// -->
	 <!-- Spring for Kafka                         -->
	 <!-- ///////////////////////////////////////// -->
		<dependency>
		    <groupId>org.springframework.kafka</groupId>
		    <artifactId>spring-kafka</artifactId>
		    <version>4.1.0</version>
		</dependency>

	</dependencies>

</project>
