<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<!-- ====================================================================== -->
	<!-- PARENT                                                                 -->
	<!-- ====================================================================== -->
	<parent>
		<groupId>r01.fabric.coreservices.messaging.rabbitmq</groupId>
		<artifactId>r01fMessagingRabbitmq</artifactId>
		<version>${revision}</version>
	</parent>
	<!-- ====================================================================== -->
	<!-- ARTIFACT                                                               -->
	<!-- ====================================================================== -->
	<name>r01fMessagingRabbitmqClasses</name>
	<artifactId>r01fMessagingRabbitmqClasses</artifactId>

	<!-- ====================================================================== -->
	<!-- DEPENDENCIES                                                           -->
	<!-- ====================================================================== -->
	<dependencies>
		<!-- ///////////////////////////////////////// -->
		<!--  Model  Classes                            -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.coreservices.messaging.common</groupId>
			<artifactId>r01fMessagingCommonBaseClasses</artifactId>
			<version>${revision}</version>
		</dependency>

		<!-- ///////////////////////////////////////// -->
		<!--  Model  Classes                            -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base</groupId>
			<artifactId>r01fMimeClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
		<!-- ///////////////////////////////////////// -->
		<!--  RabbitMQ Clients                         -->
		<dependency>
		    <groupId>com.rabbitmq</groupId>
		    <artifactId>amqp-client</artifactId>
		    <version>5.20.0</version>
		</dependency>

       	<!-- ///////////////////////////////////////// -->
		<!-- R01F: Marshaller                       -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base.objectstreamer</groupId>
			<artifactId>r01fObjectStreamerClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
	</dependencies>

</project>
