<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
 <modelVersion>4.0.0</modelVersion>

	<!-- ====================================================================== -->
	<!-- PARENT                                                                 -->
	<!-- ====================================================================== -->
	<parent>
		<groupId>r01.fabric.coreservices.cloud.google</groupId>
		<artifactId>r01fGoogle</artifactId>
		<version>${revision}</version>
	</parent>

	<!-- ====================================================================== -->
	<!-- ARTIFACT                                                               -->
	<!-- ====================================================================== -->
	<name>r01fGoogleClasses</name>
	<artifactId>r01fGoogleClasses</artifactId>

	<!-- ====================================================================== -->
	<!-- DEPENDENCIES                                                           -->
	<!-- ====================================================================== -->
	<dependencies>
		<!-- ///////////////////////////////////////// -->
		<!--  Base Classes                             -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base</groupId>
			<artifactId>r01fBaseClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
		<dependency>
			<groupId>r01.fabric.base.resourceload</groupId>
			<artifactId>r01fResourceLoadInterfaceClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>

  		<!-- ///////////////////////////////////////// -->
		<!-- GoogleAPIs                                -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
		    <groupId>com.google.api-client</groupId>
		    <artifactId>google-api-client</artifactId>
		    <version>2.4.0</version>
		    <exclusions>
		    	<exclusion>
					<groupId>com.google.guava</groupId>
					<artifactId>*</artifactId>
		    	</exclusion>
		    </exclusions>
		</dependency>
		<dependency>
		    <groupId>com.google.auth</groupId>
		    <artifactId>google-auth-library-credentials</artifactId>
		    <!--<version>1.12.1</version>-->
		    <version>1.23.0</version>
		    <exclusions>
		    	<exclusion>
					<groupId>com.google.guava</groupId>
					<artifactId>*</artifactId>
		    	</exclusion>
		    </exclusions>
		</dependency>
		<dependency>
		    <groupId>com.google.auth</groupId>
		    <artifactId>google-auth-library-oauth2-http</artifactId>
		    <version>1.12.1</version>
		     <exclusions>
		    	<exclusion>
					<groupId>com.google.guava</groupId>
					<artifactId>*</artifactId>
		    	</exclusion>
		    </exclusions>
		</dependency>

		<dependency>
		    <groupId>com.google.apis</groupId>
		    <artifactId>google-api-services-gmail</artifactId>
		    <version>v1-rev110-1.25.0</version>
		    <exclusions>
		    	<exclusion>
					<groupId>com.google.guava</groupId>
					<artifactId>*</artifactId>
		    	</exclusion>
		    </exclusions>
		</dependency>
	</dependencies>

</project>
