<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
 <modelVersion>4.0.0</modelVersion>

	<!-- ====================================================================== -->
	<!-- PARENT                                                                 -->
	<!-- ====================================================================== -->
	<parent>
		<groupId>r01.fabric.coreservices.cloud.twilio</groupId>
		<artifactId>r01fTwilio</artifactId>
		<version>${revision}</version>
	</parent>

	<!-- ====================================================================== -->
	<!-- ARTIFACT                                                               -->
	<!-- ====================================================================== -->
	<name>r01fTwilioClasses</name>
	<artifactId>r01fTwilioClasses</artifactId>

	<!-- ====================================================================== -->
	<!-- DEPENDENCIES                                                           -->
	<!-- ====================================================================== -->
	<dependencies>
		<!-- ///////////////////////////////////////// -->
		<!-- R01F: Base Classes                        -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base</groupId>
			<artifactId>r01fBaseClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>

		<!-- ///////////////////////////////////////// -->
		<!--  R01F: Base Properties                    -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base.properties</groupId>
			<artifactId>r01fPropertiesInterfaceClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>

		<!-- ///////////////////////////////////////// -->
		<!--  R01F: Notifier                           -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.coreservices.notifier</groupId>
			<artifactId>r01fNotifierClasses</artifactId>
			<version>${revision}</version>
		</dependency>

        <!-- ///////////////////////////////////////// -->
		<!-- R01: BusinessServices                     -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.businessservices</groupId>
			<artifactId>r01fBusinessServicesClasses</artifactId>
			<version>${r01f.businessservices.version}</version>
		</dependency>

  		<!-- ///////////////////////////////////////// -->
		<!-- R01: HttpClient                           -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base.httpclient</groupId>
			<artifactId>r01fHttpClientClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>

  		<!-- ///////////////////////////////////////// -->
		<!-- Twilio                                    -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
		    <groupId>com.twilio.sdk</groupId>
		    <artifactId>twilio</artifactId>
		    <version>9.16.0</version>
		</dependency>
	</dependencies>

</project>
