<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
 <modelVersion>4.0.0</modelVersion>

	<!-- ====================================================================== -->
	<!-- PARENT                                                                 -->
	<!-- ====================================================================== -->
	<parent>
		<groupId>r01.fabric.coreservices.brms</groupId>
		<artifactId>r01fBRMS</artifactId>
		<version>${revision}</version>
	</parent>

	<!-- ====================================================================== -->
	<!-- PROPERTIES                                                             -->
	<!-- ====================================================================== -->
	 <properties>
        <drools-version>9.44.0.Final</drools-version>  <!-- Last known version: 7.38.0.Final , >  8.39.0 requires Java11 -->
    </properties>

	<!-- ====================================================================== -->
	<!-- ARTIFACT                                                               -->
	<!-- ====================================================================== -->
	<name>r01fDroolsClasses</name>
	<artifactId>r01fDroolsClasses</artifactId>

	<!-- ====================================================================== -->
	<!-- DEPENDENCIES                                                           -->
	<!-- ====================================================================== -->
	<dependencies>
		<!-- ///////////////////////////////////////// -->
		<!--  Base Classes                             -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base.resourceload</groupId>
			<artifactId>r01fResourceLoadInterfaceClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
		<dependency>
			<groupId>r01.fabric.businessservices</groupId>
			<artifactId>r01fBusinessServicesClasses</artifactId>
			<version>${r01f.businessservices.version}</version>
		</dependency>
		<!-- ///////////////////////////////////////// -->
		<!-- R01f Object Streamer          				   -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base.objectstreamer</groupId>
			<artifactId>r01fObjectStreamerClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
		<!-- ///////////////////////////////////////// -->
		<!-- R01f Properties         				   -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base.properties</groupId>
			<artifactId>r01fPropertiesClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>

  		<!-- ///////////////////////////////////////// -->
		<!-- DROOLS                                -->
		<!-- ///////////////////////////////////////// -->
        <!-- ... -->
        <dependency>
            <groupId>org.kie</groupId>
            <artifactId>kie-ci</artifactId>
            <version>${drools-version}</version>
             <exclusions>
		        <exclusion>  <!-- declare the exclusion here -->
		          <groupId>org.kie.soup</groupId>
                  <artifactId>kie-soup-maven-integration</artifactId>
		        </exclusion>
		        <exclusion>  <!-- declare the exclusion here -->
		          <groupId>org.apache.maven</groupId>
                  <artifactId>maven-core</artifactId>
		        </exclusion>
      		</exclusions>
        </dependency>
        <dependency>
            <groupId>org.drools</groupId>
            <artifactId>drools-decisiontables</artifactId>
            <version>${drools-version}</version>
        </dependency>
        <dependency>
            <groupId>org.drools</groupId>
            <artifactId>drools-core</artifactId>
            <version>${drools-version}</version>
        </dependency>
        <dependency>
            <groupId>org.drools</groupId>
            <artifactId>drools-compiler</artifactId>
            <version>${drools-version}</version>
        </dependency>

    </dependencies>
</project>
