<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<!-- ====================================================================== -->
	<!-- PARENT                                                                 -->
	<!-- ====================================================================== -->
	<parent>
		<groupId>r01.fabric.coreservices.notifier</groupId>
		<artifactId>r01fNotifier</artifactId>
		<version>${revision}</version>
	</parent>

	<!-- ====================================================================== -->
	<!-- ARTIFACT                                                               -->
	<!-- ====================================================================== -->
	<name>r01fNotifierClasses</name>
	<artifactId>r01fNotifierClasses</artifactId>

	<!-- ====================================================================== -->
	<!-- DEPENDENCIES                                                           -->
	<!-- ====================================================================== -->
	<dependencies>
		<!-- ///////////////////////////////////////// -->
		<!-- R01F: Base Classes                        -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base</groupId>
			<artifactId>r01fBaseClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
		<dependency>
			<groupId>r01.fabric.base.properties</groupId>
			<artifactId>r01fPropertiesInterfaceClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
		<!-- ///////////////////////////////////////// -->
		<!--  R01F: DI                                 -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base.di</groupId>
			<artifactId>r01fDIClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
		<!-- ///////////////////////////////////////// -->
		<!-- R01F: EMail                               -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.coreservices.email</groupId>
			<artifactId>r01fEMailClasses</artifactId>
			<version>${revision}</version>
		</dependency>
	</dependencies>

</project>
