<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
 <modelVersion>4.0.0</modelVersion>

	<!-- ====================================================================== -->
	<!-- PARENT                                                                 -->
	<!-- ====================================================================== -->
	<parent>
		<groupId>r01.fabric.coreservices.cloud.google</groupId>
		<artifactId>r01fGoogle</artifactId>
		<version>${revision}</version>
	</parent>

	<!-- ====================================================================== -->
	<!-- ARTIFACT                                                               -->
	<!-- ====================================================================== -->
	<name>r01fFirebaseClasses</name>
	<artifactId>r01fFirebaseClasses</artifactId>

	<!-- ====================================================================== -->
	<!-- DEPENDENCIES                                                           -->
	<!-- ====================================================================== -->
	<dependencies>
		<!-- ///////////////////////////////////////// -->
		<!-- R01F: Base Classes                        -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base</groupId>
			<artifactId>r01fBaseClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>

		<!-- ///////////////////////////////////////// -->
		<!--  R01F: Base Properties                    -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base.properties</groupId>
			<artifactId>r01fPropertiesClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
		<!-- ///////////////////////////////////////// -->
		<!--  R01F: Notifier                           -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.coreservices.notifier</groupId>
			<artifactId>r01fNotifierClasses</artifactId>
			<version>${revision}</version>
		</dependency>
  		<!-- ///////////////////////////////////////// -->
		<!-- R01: HttpClient                           -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base.httpclient</groupId>
			<artifactId>r01fHttpClientClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
		<!-- ///////////////////////////////////////// -->
		<!-- Firebase                                    -->
		<!-- ///////////////////////////////////////// -->
		 <dependency>
		    <groupId>com.google.firebase</groupId>
		    <artifactId>firebase-admin</artifactId>
		    <version>9.3.0</version>
		    <!-- Last  version:
		         <version>9.3.0</version>-->
		</dependency>
		 <!-- There is some issue with firebase and Java9+ , analize : https://medium.com/@ygge/firebase-in-java-9-with-modules-9a4eb99cffcb -->
		<dependency>
		    <groupId>io.grpc</groupId>
		    <artifactId>grpc-context</artifactId>
		    <version>1.62.2</version>
		</dependency>
	</dependencies>

</project>
