<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<!-- ====================================================================== -->
	<!-- PARENT                                                                 -->
	<!-- ====================================================================== -->
	<parent>
		<groupId>r01.fabric.coreservices.geo</groupId>
		<artifactId>r01fGeo</artifactId>
		<version>${revision}</version>
	</parent>

	<!-- ====================================================================== -->
	<!-- ARTIFACT                                                               -->
	<!-- ====================================================================== -->
	<name>r01fGeoGuiceClasses</name>
	<artifactId>r01fGeoGuiceClasses</artifactId>

	<!-- ====================================================================== -->
	<!-- DEPENDENCIES                                                           -->
	<!-- ====================================================================== -->
	<dependencies>
		<!-- ///////////////////////////////////////// -->
		<!-- R01F: GEO                                 -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.coreservices.geo</groupId>
			<artifactId>r01fGeoClasses</artifactId>
			<version>${revision}</version>
		</dependency>
	    <!-- ///////////////////////////////////////// -->
	    <!-- ///////////////////////////////////////// -->
		<!-- Guice                                     -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base.di</groupId>
			<artifactId>r01fDIGuiceClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
	</dependencies>

</project>
