<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<!-- ====================================================================== -->
	<!-- PARENT                                                                 -->
	<!-- ====================================================================== -->
	<parent>
		<groupId>r01.fabric.coreservices.messaging.kafka</groupId>
		<artifactId>r01fMessagingKafka</artifactId>
		<version>${revision}</version>
	</parent>
	<!-- ====================================================================== -->
	<!-- ARTIFACT                                                               -->
	<!-- ====================================================================== -->
	<name>r01fMessagingKafkaGuiceClasses</name>
	<artifactId>r01fMessagingKafkaGuiceClasses</artifactId>

	<!-- ====================================================================== -->
	<!-- DEPENDENCIES                                                           -->
	<!-- ====================================================================== -->
	<dependencies>
		<!-- ///////////////////////////////////////// -->
		<!--  Kfaka Classes                            -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.coreservices.messaging.kafka</groupId>
			<artifactId>r01fMessagingKafkaClasses</artifactId>
			<version>${revision}</version>
		</dependency>
  		<!-- ///////////////////////////////////////// -->
		<!--  Messaging Guice  Classes                  -->
		<!-- /////////////////////////////////////////  -->

		<dependency>
			<groupId>r01.fabric.coreservices.messaging.common</groupId>
			<artifactId>r01fMessagingGuiceBaseClasses</artifactId>
			<version>${revision}</version>
		</dependency>
	</dependencies>

</project>
