<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

<!-- ====================================================================== -->
<!-- PARENT                                                                 -->
<!-- ====================================================================== -->
	<parent>
		<groupId>r01.fabric.coreservices.fileexplorer</groupId>
		<artifactId>r01fFileExplorer</artifactId>
		<version>${revision}</version>
	</parent>

<!-- ====================================================================== -->
<!-- ARTIFACT                                                               -->
<!-- ====================================================================== -->
	<name>r01fFileExplorerConnectorClasses</name>
	<artifactId>r01fFileExplorerConnectorClasses</artifactId>

<!-- ====================================================================== -->
<!-- DEPENDENCIES                                                           -->
<!-- ====================================================================== -->
	<dependencies>
		<!-- ///////////////////////////////////////// -->
		<!-- R01F: FRAMEWORK                           -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base.objectstreamer</groupId>
			<artifactId>r01fObjectStreamerClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
		<dependency>
			<groupId>r01.fabric.base.properties</groupId>
			<artifactId>r01fPropertiesClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
		<dependency>
			<groupId>r01.fabric.base</groupId>
			<artifactId>r01fMimeClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>

		<!-- ///////////////////////////////////////// -->
		<!-- R01F: FileStore                           -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.coreservices.filesystem</groupId>
			<artifactId>r01fHDFSFileStoreClasses</artifactId>
			<version>${revision}</version>
			<exclusions>
				<!-- Avoid version conflict, exclude servlet-api-2.5.jar -->
				<exclusion>
					<groupId>javax.servlet</groupId>
					<artifactId>servlet-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<!-- S3 -->
		<dependency>
			<groupId>r01.fabric.coreservices.filesystem</groupId>
			<artifactId>r01fS3FileStoreClasses</artifactId>
			<version>${revision}</version>
		</dependency>

		<!-- ///////////////////////////////////////// -->
		<!-- R01F: WebProfile                          -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base.web</groupId>
			<artifactId>r01fWebProfileClasses</artifactId>
			<version>${r01f.base.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.commons</groupId>
					<artifactId>commons-fileupload2-jakarta-servlet6</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<!-- ///////////////////////////////////////// -->
		<!-- ServletAPI                                -->
		<!-- ///////////////////////////////////////// -->
		<!-- [r01fWebProfileClasses] has SevletAPI as a dependency,
			 ... BUT it's SCOPE is PROVIDED so it has to be defined
			     here again -->
		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
			<version>6.0.0</version>
			<scope>provided</scope>		<!-- BEWARE!!! -->
		</dependency>

		<!-- ///////////////////////////////////////// -->
		<!-- Image                                     -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>com.mortennobel</groupId>
			<artifactId>java-image-scaling</artifactId>
			<version>0.8.6</version>
		</dependency>
	</dependencies>

<!-- ====================================================================== -->
<!-- BUILD                                                                  -->
<!-- ====================================================================== -->
	<build>
		<pluginManagement>
			<plugins>
				<!--
				ECLIPSE (see main pom.xml for further info) ===================
				This plugin has NO effects in maven build:
					m2e ONLY runs some 'standard' goals of the maven pom.xml since the aim of m2e is NOT to be a complete CI tool
					... in order to include 'non-standard' goals in m2e execution and avoid [plugin execution not covered by the eclipse m2e plugin project build lifecycle mapping]
						the 'non-standard' plugin MUST be explicitly included in m2e execution
				-->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<!-- flatten plugin -->
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>org.codehaus.mojo</groupId>
										<artifactId>flatten-maven-plugin</artifactId>
										<versionRange>[1.1.0,)</versionRange>
										<goals>
											<goal>flatten</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore></ignore>
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>
