<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<!-- ====================================================================== -->
	<!-- PARENT                                                                 -->
	<!-- ====================================================================== -->
	<parent>
		<groupId>r01.fabric.coreservices.scheduler</groupId>
		<artifactId>r01fScheduler</artifactId>
		<version>${revision}</version>
	</parent>

	<!-- ====================================================================== -->
	<!-- ARTIFACT                                                               -->
	<!-- ====================================================================== -->
	<name>r01fSchedulerClasses</name>
	<artifactId>r01fSchedulerClasses</artifactId>

	<!-- ====================================================================== -->
	<!-- DEPENDENCIES                                                           -->
	<!-- ====================================================================== -->
	<dependencies>
		<!-- ///////////////////////////////////////// -->
		<!-- Base                                      -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base</groupId>
			<artifactId>r01fBaseClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>

		<!-- ///////////////////////////////////////// -->
		<!-- Properties                                -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base.properties</groupId>
			<artifactId>r01fPropertiesClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
	    <!-- ///////////////////////////////////////// -->
		<!--  R01F: DI                                 -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base.di</groupId>
			<artifactId>r01fDIClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>

		<!-- ///////////////////////////////////////// -->
		<!-- QUARTZ                                    -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
		    <groupId>org.quartz-scheduler</groupId>
		    <artifactId>quartz</artifactId>
		    <version>${quartz.version}</version>
		</dependency>
		<dependency>
		    <groupId>org.quartz-scheduler</groupId>
		    <artifactId>quartz-jobs</artifactId>
		    <version>${quartz.version}</version>
		</dependency>
	</dependencies>

</project>
