<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<!-- ====================================================================== -->
	<!-- PARENT                                                                 -->
	<!-- ====================================================================== -->
	<parent>
		<groupId>r01.fabric.coreservices.filesystem</groupId>
		<artifactId>r01fFileSystem</artifactId>
		<version>${revision}</version>
	</parent>
	<!-- ====================================================================== -->
	<!-- ARTIFACT                                                               -->
	<!-- ====================================================================== -->
	<name>r01fS3FileStoreClasses</name>
	<artifactId>r01fS3FileStoreClasses</artifactId>

	<!-- ====================================================================== -->
	<!-- DEPENDENCIES                                                           -->
	<!-- ====================================================================== -->
	<dependencies>		
		<!-- ///////////////////////////////////////// -->
		<!-- Fabric                                 -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base</groupId>
			<artifactId>r01fModelClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
		<!-- ///////////////////////////////////////// -->
		<!-- FileStore                                 -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base.filestore</groupId>
			<artifactId>r01fFileStoreClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
		<!-- ///////////////////////////////////////// -->
		<!-- R01f: S3                				   -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.coreservices.cloud.aws.s3</groupId>
			<artifactId>r01fAWSS3Classes</artifactId>
			<version>${revision}</version>
		</dependency>
		
		<dependency>
			<groupId>r01.fabric.businessservices</groupId>
			<artifactId>r01fBusinessServicesClasses</artifactId>
			<version>${r01f.businessservices.version}</version>
		</dependency>

	</dependencies>

</project>
