<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<!-- ====================================================================== -->
	<!-- PARENT                                                                 -->
	<!-- ====================================================================== -->
	<parent>
		<groupId>r01.fabric.coreservices.messaging.rabbitmq.listeners</groupId>
		<artifactId>r01fMessagingRabbitmqListeners</artifactId>
		<version>${revision}</version>
	</parent>

	<!-- ====================================================================== -->
	<!-- ARTIFACT                                                               -->
	<!-- ====================================================================== -->
	<name>r01fRabbitmqListenerSpringBaseClasses</name>
	<artifactId>r01fRabbitmqListenerSpringBaseClasses</artifactId>

	<!-- ====================================================================== -->
	<!-- DEPENDENCIES                                                           -->
	<!-- ====================================================================== -->
	<dependencies>	

	 <!-- ///////////////////////////////////////// -->
	 <!-- Rabbit CORE                                -->
	 <!-- ///////////////////////////////////////// -->
        <dependency>
			<groupId>r01.fabric.coreservices.messaging.rabbitmq</groupId>
			<artifactId>r01fMessagingRabbitmqClasses</artifactId>
			<version>${revision}</version>
		</dependency>
	   <dependency>
			<groupId>r01.fabric.coreservices.messaging.rabbitmq</groupId>
			<artifactId>r01fMessagingRabbitmqGuiceClasses</artifactId>
			<version>${revision}</version>
		</dependency>
     <!-- ///////////////////////////////////////// -->
	 <!-- Spring for Rabbit                         -->
	 <!-- ///////////////////////////////////////// -->
		<dependency>
		    <groupId>org.springframework.amqp</groupId>
		    <artifactId>spring-amqp</artifactId>
		    <version>3.1.1</version>
		</dependency>

		<dependency>
		    <groupId>org.springframework.amqp</groupId>
		    <artifactId>spring-rabbit</artifactId>
		    <version>3.1.1</version>
		</dependency>

	</dependencies>
</project>
