# application.yml (Defaults Generales y Importación)

# === Configuración Base ===
app:
  name: My-Service-Core
  version: 1.0.0

logging:
    level:
      root: INFO
      org.hibernate.jpa.internal.util.LogHelper: INFO
# === Importar Módulos ===
spring:
  config:
    import:
      # Import db 
      - classpath:config/default/z99-s3.yml   
      - classpath:config/default/z99-s3-retriever.yml   
      - optional:classpath:config/${spring.profiles.active}/database.yml