<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

<!-- ====================================================================== -->
<!-- PARENT                                                                 -->
<!-- ====================================================================== -->
	<parent>
		<groupId>r01.fabric.coreservices.email</groupId>
		<artifactId>r01fEMail</artifactId>
		<version>${revision}</version>
	</parent>

<!-- ====================================================================== -->
<!-- ARTIFACT                                                               -->
<!-- ====================================================================== -->
	<name>r01fEMailClasses</name>
	<artifactId>r01fEMailClasses</artifactId>

<!-- ====================================================================== -->
<!-- DEPENDENCIES                                                           -->
<!-- ====================================================================== -->
	<dependencies>
		<!-- ///////////////////////////////////////// -->
		<!--  Base Classes                             -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base</groupId>
			<artifactId>r01fBaseClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
		<dependency>
			<groupId>r01.fabric.base</groupId>
			<artifactId>r01fMimeClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>

		<!-- ///////////////////////////////////////// -->
		<!-- Jakarta Mail API.                         -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>jakarta.mail</groupId>
			<artifactId>jakarta.mail-api</artifactId>
			<version>2.1.2</version>
		</dependency>
		
		<!-- ///////////////////////////////////////// -->
		<!-- Jakarta Mail API IMPL.    (provides the implementation of the Jakarta Mail Specification  -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>org.eclipse.angus</groupId>
			<artifactId>jakarta.mail</artifactId>
			<version>2.0.2</version>
		</dependency>

		<!-- Mime Support :
		     commons-email 2.0.0 which
		     .... will be compatible with the jakarta namespace will be available soon (I'm writing this answer on 2024-01-15) as you can see in this Jira ticket : https://issues.apache.org/jira/browse/EMAIL-203
		     alternative of org.simplejavamail ( change when commons-email 2.0.0 will be available...)
		-->
		<dependency>
			<groupId>org.simplejavamail</groupId>
			<artifactId>simple-java-mail</artifactId>
			<version>8.6.3</version>
		</dependency>
		
		<!-- To avoid issue with:
		     java.lang.NoClassDefFoundError: com/sun/activation/registries/LogSupport
		     https://github.com/jakartaee/mail-api/issues/627
		-->
		<dependency>
			<groupId>javax.activation</groupId>
			<artifactId>activation</artifactId>
			<version>1.1.1</version>
		</dependency>
	</dependencies>

<!-- ====================================================================== -->
<!-- BUILD                                                                  -->
<!-- ====================================================================== -->
	<build>
		<pluginManagement>
			<plugins>
				<!--
				ECLIPSE (see main pom.xml for further info) ===================
				This plugin has NO effects in maven build:
					m2e ONLY runs some 'standard' goals of the maven pom.xml since the aim of m2e is NOT to be a complete CI tool
					... in order to include 'non-standard' goals in m2e execution and avoid [plugin execution not covered by the eclipse m2e plugin project build lifecycle mapping]
						the 'non-standard' plugin MUST be explicitly included in m2e execution
				-->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<!-- flatten plugin -->
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>org.codehaus.mojo</groupId>
										<artifactId>flatten-maven-plugin</artifactId>
										<versionRange>[1.1.0,)</versionRange>
										<goals>
											<goal>flatten</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore></ignore>
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>
