<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<!-- ====================================================================== -->
	<!-- PROPERTIES                                                             -->
	<!-- ====================================================================== -->
	<properties>
		<hadoop.version>3.4.1</hadoop.version>	<!-- last known good: 2.7.3 -->
	</properties>
	<!-- ====================================================================== -->
	<!-- PARENT                                                                 -->
	<!-- ====================================================================== -->
	<parent>
		<groupId>r01.fabric.coreservices.filesystem</groupId>
		<artifactId>r01fFileSystem</artifactId>
		<version>${revision}</version>
	</parent>
	<!-- ====================================================================== -->
	<!-- ARTIFACT                                                               -->
	<!-- ====================================================================== -->
	<name>r01fParquetHandlerClasses</name>
	<artifactId>r01fParquetHandlerClasses</artifactId>

	<!-- ====================================================================== -->
	<!-- DEPENDENCIES                                                           -->
	<!-- ====================================================================== -->	
	<!-- ///////////////////////////////////////// -->
	<!-- PARQUET                                  -->
	<!-- ///////////////////////////////////////// -->
	<dependencies>
	    <dependency>
	        <groupId>org.apache.parquet</groupId>
	        <artifactId>parquet-avro</artifactId>
	        <version>1.13.1</version>
	    </dependency>
		<!-- 
		Note: this impl of Parquet uses  parquet-floor .
		      The standard impl is based on hadoop libraries an aparenttly requires a hadoop local installation
		      To Avoid this blue.strategic.parquet has been used  
		-->
		<dependency>
		    <groupId>blue.strategic.parquet</groupId>
		    <artifactId>parquet-floor</artifactId>
		    <version>1.62</version>		  
		</dependency>
		<dependency>
		    <groupId>com.github.luben</groupId>
		    <artifactId>zstd-jni</artifactId>
		    <version>1.5.7-7</version>		  
		</dependency>	
	    <dependency>
	        <groupId>org.apache.avro</groupId>
	        <artifactId>avro</artifactId>
	        <version>1.12.1</version>	        
	        <!-- include the FABRIC r01fObjectStreamer dep instead!! -->
			<exclusions>
		        <exclusion>
		            <groupId>com.fasterxml.jackson.core</groupId>
		            <artifactId>jackson-core</artifactId>
		        </exclusion>
		         <exclusion>
		            <groupId>com.fasterxml.jackson.core</groupId>
		            <artifactId>jackson-databind</artifactId>
		        </exclusion>
		    </exclusions>
	    </dependency>	    
	</dependencies>


</project>
