<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<!-- ====================================================================== -->
	<!-- PARENT                                                                 -->
	<!-- ====================================================================== -->
	<parent>
		<groupId>r01.fabric.coreservices.email</groupId>
		<artifactId>r01fEMail</artifactId>
		<version>${revision}</version>
	</parent>

	<!-- ====================================================================== -->
	<!-- ARTIFACT                                                               -->
	<!-- ====================================================================== -->
	<name>r01fEMailSpringClasses</name>
	<artifactId>r01fEMailSpringClasses</artifactId>

	<!-- ====================================================================== -->
	<!-- DEPENDENCIES                                                           -->
	<!-- ====================================================================== -->
	<dependencies>

	    <!-- ///////////////////////////////////////// -->
		<!-- R01: BusinessServices                     -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.businessservices</groupId>
			<artifactId>r01fBusinessServicesClasses</artifactId>
			<version>${r01f.businessservices.version}</version>
		</dependency>

		<!-- ///////////////////////////////////////// -->
		<!-- R01F: Notifier                            -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.coreservices.notifier</groupId>
			<artifactId>r01fNotifierClasses</artifactId>
			<version>${revision}</version>
		</dependency>

  		<!-- ///////////////////////////////////////// -->
		<!-- R01: Spring                               -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base.di</groupId>
			<artifactId>r01fDISpringClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>

  		<!-- ///////////////////////////////////////// -->
		<!-- R01: HttpClient                           -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.base.httpclient</groupId>
			<artifactId>r01fHttpClientClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>

  		<!-- ///////////////////////////////////////// -->
		<!-- R01F Cloud: Google                        -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.coreservices.cloud.google</groupId>
			<artifactId>r01fGoogleClasses</artifactId>
		    <version>${revision}</version>
		</dependency>

  		<!-- ///////////////////////////////////////// -->
		<!-- R01F Cloud: SES                           -->
		<!-- ///////////////////////////////////////// -->
		<dependency>
			<groupId>r01.fabric.coreservices.cloud.aws.ses</groupId>
			<artifactId>r01fAWSSESClasses</artifactId>
		    <version>${revision}</version>
		</dependency>
		
		
  		<!-- ///////////////////////////////////////// -->
		<!-- R01F Object Streamer                           -->
		<!-- ///////////////////////////////////////// -->
		
		<dependency>
			<groupId>r01.fabric.base.objectstreamer</groupId>
			<artifactId>r01fObjectStreamerClasses</artifactId>
			<version>${r01f.base.version}</version>
		</dependency>
		
	</dependencies>

</project>
